### PR TITLE
resolves #16 add GitHub Actions CI

### LINKED ISSUE #16: Add GitHub actions for CI
- Implement GitHub actions for Continuous Integration
- check all node versions from from Asciidoctor.js project

### PR DESCRIPTION
**Pull request by ggrossetie**
resolves #16

### CODE REVIEW

**Comment by ghost** [comment]
I will include the nice icons for CI and npm in the file README.md in the branch with the changes for Asciidoctor 2.2.0

**Comment by ggrossetie** [comment]
Perfect, I can also add the CI badge in this pull request if you want.

**Comment by ghost** [comment]
There is no README.md in the release underlying this pull request. I think it does not make too much sense to add one here and then overwrite it later.

**Comment by ggrossetie** [comment]
> There is no README.md in the release underlying this pull request. I think it does not make too much sense to add one here and then overwrite it later.

Ah you're right :grimacing: 
Let me know if you want to change something before merging.

**Comment by ghost** [comment]
Node 14.x is not in the list of node versions. Is it not supported?

**Comment by ggrossetie** [comment]
You are right, it should be 12 (current LTS) and 14 (latest stable). I will update it.

**Comment by ghost** [comment]
Perfect! You can merge the request now

**Pull request merged**
